#!/bin/zsh
#
# Copyright 2022 Stéphane Caron

PI3HAT_CFG="1=1,2,3;2=4,5,6"

for ((i=1; i<=6; i++)); do
    sudo moteus_tool --pi3hat-cfg "${PI3HAT_CFG}" --zero-offset -t $i
done

servo_tool --pi3hat-cfg "${PI3HAT_CFG}" stats
touch /tmp/rezero_success
